### PR TITLE
added calculator app example

### PR DESCRIPTION
**Pull request by harshil1712**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@harshil1712  there is no readme in your app folder. Please add reame as per the contribution Guideline also i used the `contributors.md` format please use that to add your name in that file. Also make sure to sync your fork with this original issue and fix the `conflict` above.

**Comment by sagarchoudhary96** [comment]
hey @harshil1712  sorry for that, the readme is there.  Also i referred to contributers.md only there are conflits in PR as you can see resolve the conflicts and add your name as `* [your_name](your_github_url)`

**Comment by harshil1712** [comment]
@sagarchoudhary96 solved the merge conflict

**Comment by sagarchoudhary96** [comment]
close #7 #4

**Pull request merged**
